=== Yassirelhanafi/xmlproject/livres.dtd
<!ELEMENT cloud_hybrid (overview, ecosysteme,technologies, use_cases, security, future)>

<!ELEMENT overview (overview_question,overview_content , overview_importance )>
<!ELEMENT overview_question (#PCDATA)>
<!ELEMENT overview_content (#PCDATA)>
<!ELEMENT overview_importance (#PCDATA)>

<!ELEMENT ecosysteme (content_container, plateforme_container)>
<!ELEMENT content_container (content , list*)>
<!ELEMENT content (#PCDATA )>
<!ELEMENT plateforme_container (plateforme , list*)>
<!ELEMENT plateforme (#PCDATA )>


<!ELEMENT technologies (technology+)>
<!ELEMENT technology (tech_name, tech_description, image?)>
<!ELEMENT tech_name (#PCDATA)>
<!ELEMENT tech_description (#PCDATA | list)*>
<!ELEMENT list (item+)>
<!ELEMENT item (#PCDATA)>
<!ELEMENT image (#PCDATA)>

<!ELEMENT use_cases (use_case+)>
<!ELEMENT use_case (usecase_title, user_container, image?)>
<!ELEMENT usecase_title (#PCDATA)>
<!ELEMENT usecase_description (#PCDATA)>
<!ELEMENT user_container (usecase_description , list*)>

<!ELEMENT security (strategy+)>
<!ELEMENT strategy (security_title, security_container)>
<!ELEMENT security_title (#PCDATA)>
<!ELEMENT security_container (security_details , list*)>
<!ELEMENT security_details (#PCDATA)>

<!ELEMENT future (trend+)>
<!ELEMENT trend (trend_title, trend_description, image?)>
<!ELEMENT trend_title (#PCDATA)>
<!ELEMENT trend_description (#PCDATA)>

=== Yassirelhanafi/xmlproject/livres.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="livres.xsl"?>
<!DOCTYPE cloud_hybrid SYSTEM "livres.dtd">
<cloud_hybrid>
    <overview>
        <overview_question>Qu'est ce que le cloud hybride ? </overview_question>
        <overview_content> Un cloud hybride est un environnement informatique mixte dans lequel les applications sont exécutées en utilisant une combinaison de calculs, de stockage et de services dans différents environnements (clouds publics et clouds privés), y compris des centres de données sur site ou des emplacements "périphériques". Les approches de cloud computing hybrides sont très répandues, car presque personne ne s'appuie entièrement sur un seul cloud public aujourd'hui.

            Les solutions de cloud hybride vous permettent de migrer et de gérer des charges de travail entre ces différents environnements cloud, ce qui vous permet de créer des configurations plus polyvalentes selon les besoins spécifiques de votre entreprise. De nombreuses entreprises choisissent d'adopter des plates-formes cloud hybrides pour réduire les coûts, minimiser les risques et étendre leurs capacités existantes afin de soutenir leurs efforts de transformation numérique.
            
            L'approche cloud hybride est l'une des configurations d'infrastructure les plus courantes aujourd'hui. Les migrations vers le cloud mènent souvent à des implémentations de cloud hybride, car les entreprises doivent souvent faire migrer leurs applications et leurs données de manière lente et systématique. Les environnements cloud hybrides vous permettent de continuer à utiliser les services sur site tout en profitant des options flexibles de stockage et d'accès aux données et aux applications proposées par les fournisseurs de cloud public tels que Google Cloud.     
        </overview_content>
        <overview_importance>
            Nombreuses sont les entreprises qui rencontrent un franc
succès en fournissant des services Cloud privés et qui ont
parallèlement pu tenter l'expérience des services Cloud publics.
Plus l'entreprise reconnaît les avantages du Cloud Computing
et se lance dans l'aventure, plus la demande concernant les
services existants s'accentue. Un Cloud hybride permet au
département informatique de gagner en flexibilité en jonglant
entre les ressources de systèmes Cloud privés et publics, via un
environnement d'exploitation unique, automatisé et orchestré.
Un Cloud hybride permet également au département
informatique d'optimiser les ressources face à ses différents
besoins et de diversifier les exigences liées aux charges de
travail. Comme ces exigences varient d'une entreprise à l'autre,
le Cloud hybride n'est pas une solution à « taille unique ».
En effet, pour des systèmes évolutifs et commercialisables
rapidement, le Cloud public est la meilleure option à
envisager. Concernant les anciens systèmes, le Cloud privé
ou le Cloud public SaaS seraient plus adaptés pour des
fonctions standardisées. Les systèmes professionnels centraux
s'exécutent généralement sur un système Cloud privé interne.
Le Cloud hybride permet également à une entreprise
d'équilibrer son besoin d'investissement dans des technologies
Cloud sur site (dépenses en capital), avec une utilisation
des services Cloud publics hors-site (frais d'exploitation), en
passant par un modèle de déploiement de type « créer la
base, louer les services de gestion des pics ». Ainsi, elle peut
optimiser son coût de revient.
        </overview_importance>
    </overview>
    <ecosysteme>
        <content_container>
            <content>
                L'idée d'écosystèmes Cloud ouverts et extensibles relie les services
            Cloud (public et privé) d'une entreprise au sein d'un écosystème aux
            notions de portabilité et d'interconnectivité. Ces deux aspects sont
            des problématiques à prendre en compte à chaque couche d'un
            Cloud hybride. Pour les pallier, il faut se tourner vers les normes
            ouvertes.
            L'Open Data Center Alliance a défini des exigences pour les modèles
            d'utilisation de chaque couche de service concernant l'interopérabilité
            et l'interconnectivité, notamment :
        </content>
        <list>
            <item>Portabilité IaaS. Possibilité de déplacer des images ou des
                instances physiques ou virtuelles (incluant connectivité réseau et
                stockage) entre des environnements sur de courtes ou longues
                distances, avec certaines caractéristiques telles qu'une facilité de
                gestion, la migration dynamique ou au repos, des performances
                élevées et la distance.
            </item>
            <item>
                Interconnexion PaaS et portabilité des applications. Possibilité
                de déplacer des applications (et des structures de données
                logiques associées) entre différents environnements PaaS (de
                développement et d'exécution), avec des applications orientées
                Cloud qui gèrent des attributs comme des ensembles de
                caractéristiques, une structure paramétrable et une orchestration.
            </item>
            <item>
                Interconnexion SaaS et portabilité. Possibilité de connecter ou
                de transférer des informations et fonctionnalités de processus
                de travail via une infrastructure SaaS, et de créer des applications
                composites à partir d'infrastructures SaaS et non SaaS, via des
                interfaces compatibles qui échangent des données de façon fluide.
            </item>
        </list>
        </content_container>
        <plateforme_container>
            <plateforme>
                Une plate-forme de gestion de Cloud (Cloud management platform,
                CMP) est un logiciel intégré qui fournit la qualité de service, la sécurité
                et la disponibilité nécessaires aux charges de travail qui s'exécutent
                dans des environnements Cloud. Les offres d'une plate-forme de
                gestion de Cloud varient grandement en termes de maturité, de
                complexité d'architecture et de capacités. Votre choix peut simplifier
                le développement de l'administrabilité, de l'automatisation et de
                l'orchestration dans des environnements Cloud publics.
                Une plate-forme de gestion du Cloud doit au minimum fournir
                un accès utilisateur direct au système, des fonctionnalités et
                des interfaces en libre-service, un moteur de flux de travail, un
                approvisionnement automatisé, ainsi que des fonctions de mesure et
                de refacturation.
                Les environnements Cloud hybrides utilisent davantage de capacités
                avancées, par exemple :
            </plateforme>
            <list>
                <item>Gestion des performances et des capacités</item>
                <item> Interopérabilité entre des offres d'infrastructures IaaS privées et publiques</item>
                <item>Connectivité à des Cloud externes et gestion de ces systèmes</item>
                <item>Prise en charge des applications tout au long de leur cycle de vie</item>
                <item>Catalogues de services d'arrière-plan</item>
                <item>Intégration avec des systèmes de gestion d'entreprises externes</item>

            </list>
        </plateforme_container>
           
        
            
       
      
      
    </ecosysteme>
    <technologies>
        <technology>
            <tech_name>Virtualisation</tech_name>
            <tech_description>Le cloud hybride est étroitement lié à la virtualisation, qui joue un rôle clé dans la gestion des ressources informatiques au sein de ce modèle.
                Dans un environnement de cloud hybride, la virtualisation facilite le déploiement et la gestion des applications sur différents clouds (publics et privés). Les entreprises peuvent facilement déplacer des applications et des données entre ces environnements en fonction de leurs besoins, ce qui est particulièrement utile lors de pics d'activité ou pour le "cloud bursting" — une technique qui permet d'utiliser temporairement des ressources supplémentaires dans le cloud public lorsque les ressources privées sont saturées
            </tech_description>
            <image><![CDATA[https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6wE7hGqaW7dQ4XrmPt7HJcEhHyNrx5tP0FA&s]]></image>
        </technology>
        <technology>
            <tech_name>API et Intégration</tech_name>
            <tech_description>
                Les API (Interfaces de Programmation d'Applications) sont essentielles pour l'intégration et l'interopérabilité des systèmes dans un environnement de cloud hybride, combinant des ressources de cloud public et privé pour offrir flexibilité, sécurité et contrôle des données sensibles. Elles facilitent la communication entre systèmes, permettant l'échange de données et la migration d'applications entre différents environnements. De plus, les API simplifient la migration des données en assurant une synchronisation efficace, gérant les différences de format et de technologie, et consolidant l'accès aux données provenant de sources variées. Elles garantissent également l'intégrité des données migrées et permettent l'automatisation des processus de migration en envoyant des notifications en temps réel pour une gestion proactive.
                            </tech_description>
            <image><![CDATA[https://chisellabs.com/glossary/wp-content/uploads/2021/06/What-is-an-API.png]]></image>
        </technology>
        <technology>
            <tech_name>Orchestration et Automatisation</tech_name>
            <tech_description>
